# Generated by Django 4.2.16 on 2024-10-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profile_avatar_profile_birth_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(default="default.jpg", upload_to="profile_images"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(),
        ),
    ]
